first_name_field_loc = '//input[@id="firstname"]'
last_name_field_loc = '//input[@id="lastname"]'
last_name_empty_error_loc = '//div[@id="lastname-error"]'
email_field_loc = '//input[@id="email_address"]'
password_field_loc = '//input[@id="password"]'
confirm_password_field_loc = '//input[@id="password-confirmation"]'
create_account_button_loc = '//button[@title="Create an Account"]'
js_injection_error_loc = '//div[@data-ui-id="message-error"]'
