products_list_loc = '//li[@class="item product product-item"]'
price_button_loc = '//div[normalize-space()="Price"]'
price_range_40_50_loc = '//span[normalize-space()="$49.99"]'
choose_size_button_loc = '//div[@aria-label="Size"]/div[@index="0"]'
choose_color_button_loc = '//div[@aria-label="Color"]/div[@index="1"]'
add_to_cart_button_loc = '//button[@title="Add to Cart"]'
cart_button_loc = '//a[@class="action showcart"]'
product_name_in_cart_loc = '//strong[@class="product-item-name"]'
product_price_in_cart_loc = '//div[@class="price-container"]'
