from playwright.sync_api import Page, expect


def test_demoqa_form(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    first_name_field = page.get_by_placeholder('First Name')
    first_name_field.fill('Homer')
    last_name_field = page.get_by_placeholder('Last Name')
    last_name_field.fill('Simpson')
    e_mail_field = page.get_by_placeholder('name@example.com')
    e_mail_field.fill('test@test.test')
    page.get_by_text('Male', exact=True).click()
    mobile_number_field = page.get_by_placeholder('Mobile Number')
    mobile_number_field.fill('1234567890')
    date_of_birth_field = page.locator('//input[@id="dateOfBirthInput"]')
    date_of_birth_field.fill('11 may 1980')
    date_of_birth_field.press('Escape')
    subjects_field = page.locator('//input[@id="subjectsInput"]')
    subjects_field.fill('English')
    subjects_field.press('Enter')
    page.get_by_text('Sports').click()
    current_address_field = page.get_by_placeholder('Current Address')
    current_address_field.fill('Test address')
    state_dropdown = page.locator('//input[@id="react-select-3-input"]')
    state_dropdown.fill('Haryana')
    state_dropdown.press('Enter')
    city_dropdown = page.locator('//input[@id="react-select-4-input"]')
    city_dropdown.fill('Karnal')
    city_dropdown.press('Enter')
    page.locator('//button[@id="submit"]').click()
